[input_gamepad]
#filter_name = "Steam Controller"
# 0x28DE (valve)
filter_vendor_id = 0x28DE
# 0x1304 (puck), 0x1302 (usb), 0x1303 (bt)
filter_product_id = [0x1304,0x1302,0x1303]

[simulate_gamepad]
name = "Microsoft X-Box 360 pad"
vendor_id = 0x045E
product_id = 0x028E
version = 0x114
enable_rumble = true

[behavior]
# whether dpad should be emulated as dpad buttons. If disabled, button mappings with dpad = true flag will be disabled.
dpad_to_dpad = false
# whether dpad should be emulated as hat0 (recommended). If enabled, other mappings to hat0 will be ignored.
dpad_to_hat = true

[sdl_hints]
SDL_JOYSTICK_LINUX_DEADZONES = "1"

[button_map]
"south" = "south"
"east" = "east"
"north" = "north"
"west" = "west"
"dpad_down" = { key = "dpad_down", dpad = true }
"dpad_up" = { key = "dpad_up", dpad = true }
"dpad_left" = { key = "dpad_left", dpad = true }
"dpad_right" = { key = "dpad_right", dpad = true }
"start" = "start"
"back" = "select"
"left_shoulder" = "tl"
"right_shoulder" = "tr"
"left_stick" = "thumbl"
"right_stick" = "thumbr"
# steam button
"guide" = "mode"
# quick access button
"misc1" = "base"
"left_paddle1" = "trigger_happy1"
"right_paddle1" = "trigger_happy2"
"left_paddle2" = "trigger_happy3"
"right_paddle2" = "trigger_happy4"

[axis_map]
# match xbox 360 evdev behavior by emitting trigger values in 0-255 range
"left_trigger" = { key = "z", out_range = [0,255] }
"right_trigger" = { key = "rz", out_range = [0,255] }
"leftx" = "x"
"rightx" = "rx"
"lefty" = "y"
"righty" = "ry"
